<?php

namespace monolitum\backend\params;

class Active_Get_Path_Top_AndShift extends Active_Abstract_ValidatedValue
{

    /**
     * @var Manager_Path
     */
    private $manager;

   public function __construct($type)
   {
       parent::__construct($type);
   }

    /**
     * @param Manager_Path $manager
     */
    public function setManager($manager)
    {
        $this->manager = $manager;
    }

    public function getValidatedValue()
    {
        $vv = parent::getValidatedValue();
        if($vv == null){
            $this->manager->shiftElement($this);
        }
        return parent::getValidatedValue(); // TODO: Change the autogenerated stub
    }
}
