<?php

namespace monolitum\backend\params;

class Active_Param_Path_CurrentElement extends Active_Param_Abstract
{

    /**
     * @var Manager_Path
     */
    private $manager;

    public function __construct($type)
    {
        parent::__construct($type);
    }

    /**
     * @param Manager_Path $manager
     */
    public function setManager($manager)
    {
        $this->manager = $manager;
    }

    public function getValidatedValue()
    {
        $vv = parent::getValidatedValue();
        if($vv == null){
            $this->manager->currentElement($this);
        }
        return parent::getValidatedValue(); // TODO: Change the autogenerated stub
    }
}
