<?php

namespace monolitum\bootstrap;

use monolitum\core\GlobalContext;
use monolitum\backend\params\Link;
use monolitum\backend\params\Path;
use monolitum\core\Renderable_Node;
use monolitum\backend\res\Active_Resolve_Href;
use monolitum\backend\res\HrefResolver;
use monolitum\frontend\html\HtmlElement;

class A extends AbstractText
{

    /**
     * @var Link|Path
     */
    private $href;
    /**
     * @var HrefResolver
     */
    private $hrefResolver;

    public function __construct($builder = null)
    {
        parent::__construct(new HtmlElement("a"), $builder);
    }

    /**
     * @param Link|Path $href
     */
    public function setHref($href)
    {
        $this->href = $href;
    }

    protected function afterBuildNode()
    {

        if($this->href){
            $active = new Active_Resolve_Href($this->href);
            GlobalContext::add($active);
            $this->hrefResolver = $active->getHrefResolver();
        }

        parent::afterBuildNode();
    }

    public function render()
    {
        $a = $this->getElement();

        if($this->hrefResolver){
            $a->setAttribute("href", $this->hrefResolver->resolve());
        }else{
            $a->setAttribute("href", "#");
        }

        return parent::render(); // TODO: Change the autogenerated stub
    }

    /**
     * @param string|Renderable_Node $content
     * @return A
     */
    public static function of($content)
    {
        $fc = new A();
        $fc->append($content);
        return $fc;
    }

    /**
     * @param callable $builder
     * @return A
     */
    public static function build($builder = null)
    {
        return new A($builder);
    }

    /**
     * @param callable $builder
     * @return A
     */
    public static function add($builder = null)
    {
        $fc = new A($builder);
        GlobalContext::add($fc);
        return $fc;
    }

}