<?php

namespace monolitum\bootstrap;

use monolitum\bootstrap\values\BSColor;
use monolitum\core\GlobalContext;
use monolitum\frontend\html\HtmlElement;

class Alert extends BSElementComponent
{

    /**
     * @var BSColor
     */
    private $color;

    public function __construct($builder = null)
    {
        parent::__construct(new HtmlElement("div"), $builder);
    }

    /**
     * @param BSColor $color
     */
    public function setAlertColor($color)
    {
        $this->color = $color;
    }

    protected function afterBuildNode()
    {
        $this->addClass("alert");

        if($this->color !== null){
            $this->addClass("alert-" . $this->color->getValue());
        }

        parent::afterBuildNode(); // TODO: Change the autogenerated stub
    }

    /**
     * @param callable $builder
     * @return Alert
     */
    public static function add($builder)
    {
        $fc = new Alert($builder);
        GlobalContext::add($fc);
        return $fc;
    }

}