<?php
namespace monolitum\bootstrap;

use monolitum\backend\params\Path;
use monolitum\core\Find;
use monolitum\core\GlobalContext;
use monolitum\frontend\component\CSSLink;
use monolitum\frontend\component\JSScript;
use monolitum\frontend\form\FormControl;
use monolitum\frontend\html\HtmlElement;

class FormControl_TextArea_Html extends FormControl
{

    /**
     * @param callable|null $builder
     */
    public function __construct(callable $builder = null)
    {
        parent::__construct(new HtmlElement("textarea"), $builder);
        $this->addClass("js-lite-editor");
    }

    public function convertToHidden()
    {
        $element = $this->getElement();
        if($element->getTag() === "textarea"){
            $element->setTag("input");
            $element->setAttribute("type", "hidden");

            // Replace content inside textarea to value attribute
            $content = $element->getContentAsString();
            if($content != null)
                $this->setValue($content);
        }
    }

    protected function afterBuildNode()
    {
        $element = $this->getElement();
        if($element->getTag() === "textarea") {
            /** @var BSPage $page */
            $page = Find::sync(BSPage::class);
            if (!$page->getConstant("js-lite-editor")) {
                CSSLink::addLocal(Path::ofRelativeToClass(BSPage::class, "res_lite_editor", "css", "lite-editor.min.css"));
                JSScript::addLocal(Path::ofRelativeToClass(BSPage::class, "res_lite_editor", "js", "lite-editor.min.js"));
                JSScript::addLocal(Path::ofRelativeToClass(BSPage::class, "res_lite_editor", "js", "lite-editor-activation.js"));
                $page->setConstant("js-lite-editor");
            }
        }

        parent::afterBuildNode(); // TODO: Change the autogenerated stub
    }

    /**
     * @param callable $builder
     * @return FormControl_TextArea_Html
     */
    public static function add($builder)
    {
        $fc = new FormControl_TextArea_Html($builder);
        GlobalContext::add($fc);
        return $fc;
    }

}

