<?php
namespace monolitum\bootstrap;

use monolitum\core\GlobalContext;
use monolitum\frontend\form\Form_Submit;
use monolitum\frontend\html\HtmlElement;

class FormSubmit extends Form_Submit
{

    public function __construct(callable $builder)
    {
        parent::__construct(new HtmlElement("button"), $builder);
        $this->getElement()->setAttribute("type", "submit");
        $this->getElement()->setRequireEndTag(true);
    }

    protected function buildNode()
    {
        parent::buildNode();
        $this->addClass("btn");
        $this->addClass("btn-primary");
    }

    protected function afterBuildNode()
    {
        parent::afterBuildNode(); // TODO: Change the autogenerated stub
    }

    public function afterBuildForm()
    {

        $prefix = $this->form->_getSubmitPrefix();
        $action = $this->getAction();

        $name = ($prefix !== null ? $prefix : "") .  ($action !== null ? $action : "");
        if(!empty($name)){
            $this->setAttribute("name", $name);
        }

        $method = $this->form->_getSubmitMethod();
        if($method !== null){
            $this->setAttribute("formmethod", $method);
        }


        $linkResolver = $this->form->_getSubmitLink();
        if($linkResolver !== null){
            $this->setAttribute("formaction", $linkResolver, false);
        }

    }

    /**
     * @param callable $builder
     * @return FormSubmit
     */
    public static function add($builder)
    {
        $fc = new FormSubmit($builder);
        GlobalContext::add($fc);
        return $fc;
    }

}

