<?php

namespace monolitum\bootstrap;

use monolitum\core\GlobalContext;
use monolitum\backend\res\Active_Resolve_Res;
use monolitum\backend\params\Path;
use monolitum\backend\res\ResResolver;
use monolitum\frontend\html\HtmlElement;

class Img extends BSElementComponent
{

    /**
     * @var Path
     */
    private $source;
    /**
     * @var ResResolver
     */
    private $sourceResolver;

    public function __construct($builder = null)
    {
        parent::__construct(new HtmlElement("img"), $builder);
    }

    /**
     * TODO svg
     * @param Path $path
     */
    public function setSource($path)
    {
        $this->source = $path;
    }

    protected function afterBuildNode()
    {
        if($this->source){
            $active = new Active_Resolve_Res($this->source);
            GlobalContext::add($active);
            $this->sourceResolver = $active->getResResolver();
        }

        parent::afterBuildNode();
    }

    public function render()
    {
        $img = $this->getElement();

        if($this->sourceResolver){
            $img->setAttribute("src", $this->sourceResolver->resolve());
        }

        return parent::render(); // TODO: Change the autogenerated stub
    }

    /**
     * @param callable $builder
     * @return Img
     */
    public static function add($builder = null)
    {
        $fc = new Img($builder);
        GlobalContext::add($fc);
        return $fc;
    }

}