<?php

namespace monolitum\bootstrap\values;

use monolitum\frontend\ElementComponent;

class BSColSpanResponsive extends Responsive implements BSBuiltIntoInterface
{

    /**
     * @param BSColSpan $def
     */
    public function __construct($def)
    {
        parent::__construct($def);
    }

    /**
     * @param BSColSpan $sm
     * @return BSColSpanResponsive
     */
    public function sm($sm)
    {
        return parent::sm($sm); // TODO: Change the autogenerated stub
    }

    /**
     * @param BSColSpan $md
     * @return BSColSpanResponsive
     */
    public function md($md)
    {
        return parent::md($md); // TODO: Change the autogenerated stub
    }

    /**
     * @param BSColSpan $lg
     * @return BSColSpanResponsive
     */
    public function lg($lg)
    {
        return parent::lg($lg); // TODO: Change the autogenerated stub
    }

    /**
     * @param BSColSpan $xl
     * @return BSColSpanResponsive
     */
    public function xl($xl)
    {
        return parent::xl($xl); // TODO: Change the autogenerated stub
    }

    /**
     * @param BSColSpan $xxl
     * @return BSColSpanResponsive
     */
    public function xxl($xxl)
    {
        return parent::xxl($xxl); // TODO: Change the autogenerated stub
    }

    /**
     * @param BSColSpan $def
     * @return BSColSpanResponsive
     */
    public static function of($def = null)
    {
        return new BSColSpanResponsive($def);
    }

    /**
     * @param ElementComponent $component
     * @param bool $inverted
     * @return void
     */
    public function buildInto($component, $inverted = false)
    {
        parent::_buildInto($component, "col", $inverted);
    }

}