<?php

namespace monolitum\bootstrap\values;

class BSJustifyContentResponsive extends Responsive implements BSBuiltIntoInterface
{

    /**
     * @param BSTextAlign $def
     */
    public function __construct($def)
    {
        parent::__construct($def);
    }

    /**
     * @param BSJustifyContent $sm
     * @return BSJustifyContentResponsive
     */
    public function sm($sm)
    {
        return parent::sm($sm); // TODO: Change the autogenerated stub
    }

    /**
     * @param BSJustifyContent $md
     * @return BSJustifyContentResponsive
     */
    public function md($md)
    {
        return parent::md($md); // TODO: Change the autogenerated stub
    }

    /**
     * @param BSJustifyContent $lg
     * @return BSJustifyContentResponsive
     */
    public function lg($lg)
    {
        return parent::lg($lg); // TODO: Change the autogenerated stub
    }

    /**
     * @param BSJustifyContent $xl
     * @return BSJustifyContentResponsive
     */
    public function xl($xl)
    {
        return parent::xl($xl); // TODO: Change the autogenerated stub
    }

    public function buildInto($component)
    {
        parent::_buildInto($component, "justify-content");
    }

}