<?php

namespace monolitum\bootstrap\style;

use monolitum\bootstrap\values\BSBuiltIntoInterface;
use monolitum\bootstrap\values\Responsive;
use monolitum\core\GlobalContext;
use monolitum\frontend\ElementComponent_Ext;

class BSTextAlignResponsive extends Responsive implements BSBuiltIntoInterface
{

    /**
     * @param BSTextAlign $def
     */
    public function __construct($def)
    {
        parent::__construct($def);
    }

    /**
     * @param BSTextAlign $def
     * @return BSTextAlignResponsive
     */
    public static function xs($def = null)
    {
        return new BSTextAlignResponsive($def);
    }

    /**
     * @param BSTextAlign $sm
     * @return BSTextAlignResponsive
     */
    public function sm($sm)
    {
        return parent::sm($sm); // TODO: Change the autogenerated stub
    }

    /**
     * @param BSTextAlign $md
     * @return BSTextAlignResponsive
     */
    public function md($md)
    {
        return parent::md($md); // TODO: Change the autogenerated stub
    }

    /**
     * @param BSTextAlign $lg
     * @return BSTextAlignResponsive
     */
    public function lg($lg)
    {
        return parent::lg($lg); // TODO: Change the autogenerated stub
    }

    /**
     * @param BSTextAlign $xl
     * @return BSTextAlignResponsive
     */
    public function xl($xl)
    {
        return parent::xl($xl); // TODO: Change the autogenerated stub
    }

    /**
     * @param BSTextAlign $xxl
     * @return BSTextAlignResponsive
     */
    public function xxl($xxl)
    {
        return parent::xxl($xxl); // TODO: Change the autogenerated stub
    }

    public function add(){
        GlobalContext::add(
            new ElementComponent_Ext(
                function (ElementComponent_Ext $it) {
                    $this->buildInto($it->getElementComponent());
                })
        );
    }

    public function buildInto($component)
    {
        parent::_buildInto($component, "text");
    }

}
