<?php

namespace monolitum\core;

use monolitum\core\util\ListUtils;
use monolitum\backend\router\Router_Panic;
use monolitum\core\panic\DevPanic;
use monolitum\frontend\component\Head;
use monolitum\frontend\Rendered;

abstract class Renderable_Node extends Node implements Active {

    /**
     * @var null|Renderable_Node|Renderable|array<Renderable_Node|Renderable>
     */
    private $renderableChildren = null;

    public function __construct($builder = null)
    {
        parent::__construct($builder);
    }

    public static function isAppendableRenderableNode(Active $active)
    {
        return $active instanceof Renderable_Node
            && !($active instanceof Head)
            && !($active instanceof Router_Panic);
    }

    /**
     * @param Renderable_Node|Renderable $active
     * @param int|null $idx
     * @return $this
     */
    public function append($active, $idx=null)
    {
        ListUtils::insertAnElementIntoAnArray($this->renderableChildren, $this->buildRenderable($active), $idx);
        return $this;
    }

    /**
     * @param Renderable_Node|Renderable $active
     * @return mixed
     */
    public function buildRenderable($active)
    {
        if ($active instanceof Renderable_Node) {
            if ($active->isBuilt() && $active->getParent() !== $this)
                throw new DevPanic("Component has a parent.");
            if ($this->isBuilding()){
                return $this->buildChild($active);
            }else{
                return $active;
            }
        }else if(is_array($active)){
            return Rendered::of($active);
        }else if(is_string($active)){
            return Rendered::of($active);
        }else {
            return $active;
        }
    }

    protected function receiveActive($active)
    {
        if(Renderable_Node::isAppendableRenderableNode($active)){
            $this->append($active);
            return true;
        }
        return parent::receiveActive($active); // TODO: Change the autogenerated stub
    }

    protected function buildNode()
    {
        if(is_array($this->renderableChildren)){
            foreach ($this->renderableChildren as $child) {
                if($child instanceof Node)
                    $this->buildChild($child);
            }
        }else {
            if($this->renderableChildren instanceof Node)
                $this->buildChild($this->renderableChildren);
        }
        parent::buildNode(); // TODO: Change the autogenerated stub
    }

    protected function executeNode()
    {
        if(is_array($this->renderableChildren)){
            foreach ($this->renderableChildren as $child) {
                if($child instanceof Node)
                    $this->executeChild($child);
            }
        }else{
            if($this->renderableChildren instanceof Node)
                $this->executeChild($this->renderableChildren);
        }
        parent::executeNode(); // TODO: Change the autogenerated stub
    }

    function onNotReceived()
    {
        // TODO: Implement onNotReceived() method.
    }

    /**
     * @return Renderable|array|null
     */
    public function render()
    {
        return $this->renderChilds();
    }

    /**
     * @return Renderable|array|null
     */
    public function renderChilds()
    {
//        if(is_array($this->childs)){
//            $rendered = [];
//            foreach ($this->childs as $child) {
//                if($child instanceof Renderable_Node)
//                    $rendered[] = $child->render();
//                else if($child instanceof Renderable)
//                    $rendered[] = $child;
//            }
//            return $rendered;
//        }else{
//            if($this->childs instanceof Renderable_Node)
//                return $this->childs->render();
//            else if($this->childs instanceof Renderable)
//                return $this->childs;
//        }
//        return null;
        return Renderable_Node::renderArray($this->renderableChildren);
    }

    /**
     * @return Renderable|array|null
     */
    public static function renderArray($array)
    {
        if(is_array($array)){
            $rendered = [];
            foreach ($array as $child) {
                if($child instanceof Renderable_Node)
                    $rendered[] = $child->render();
                else if($child instanceof Renderable)
                    $rendered[] = $child;
            }
            return $rendered;
        }else{
            if($array instanceof Renderable_Node)
                return $array->render();
            else if($array instanceof Renderable)
                return $array;
        }
        return null;

    }

    /**
     * @param array|Renderable_Node|Renderable $rendered
     * @param mixed $element
     * @return void
     */
    public static function renderRenderedTo($rendered, $element)
    {

        if(is_array($rendered)){
            foreach ($rendered as $rendered2) {
                Renderable_Node::renderRenderedTo($rendered2, $element);
            }
        }else if($rendered instanceof Renderable_Node){
            Renderable_Node::renderRenderedTo($rendered->render(), $element);
        }else if($rendered instanceof Renderable) {
            $rendered->renderTo($element);
        }

    }


}
